import {Dimensions, StyleSheet} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  Imagess: {
    width: windowWidth,
    height: windowWidth * 0.6,
  },
  alan2: {
    backgroundColor: 'white',
    width: windowWidth * 1,
    height: 810,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
  },
  text1: {
    fontWeight: 'bold',
    fontSize: 20,
    color: 'black',
    margin: 15,
  },
  categories1: {
    flexDirection: 'row',
    gap: 8,
  },
  categoriesKupa: {
    padding: 39,
    height: 55,
    backgroundColor: '#FFFADC',
    borderRadius: 15,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: 95,
    marginLeft: 4,
  },
  kupaImage: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: 45,
    height: 45,
  },
  categoriesAtes1: {
    padding: 39,
    height: 55,
    backgroundColor: '#FBEDE0',
    borderRadius: 15,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: 95,
  },
  categorieskalp: {
    padding: 39,
    height: 55,
    backgroundColor: '#F7E9F5',
    borderRadius: 15,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: 95,
  },
  categoriesparfmm: {
    padding: 39,
    height: 55,
    backgroundColor: '#E6F0E7',
    borderRadius: 15,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: 95,
  },
  heartImage: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: 45,
    height: 45,
    tintColor: '#D296CB',
  },
  alan3: {
    backgroundColor: '#F5F9F9',
    width: 397,
    height: 165,
    borderRadius: 35,
    margin: 10,
  },
  alan3Categories: {
    flexDirection: 'row',
    gap: 5,
  },
  normalSkin: {
    padding: 39,
    height: 55,
    backgroundColor: '#FFEEF6',
    borderRadius: 15,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: 95,
  },
  gruop1: {
    width: windowWidth * 0.9,
    height: windowWidth * 0.5,
    backgroundColor: '#F5F9FA',
    borderRadius: 20,
    marginLeft: 16,
    marginTop: 30,
  },
  group12: {
    flexDirection: 'row',
    gap: 18,
    margin: 10,
  },
  dairegroup1: {
    padding: 15,
    width: 15,
    borderRadius: 47,
    backgroundColor: 'grey',
  },
  group12Text: {
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
  },
  group12Text2: {
    fontWeight: '300',
    fontSize: 10,
    color: 'black',
  },
  groupImage: {
    width: windowWidth * 0.8,
    height: windowWidth * 0.3,
    backgroundColor: 'red',
    margin: 18,
    borderRadius: 20,
  },
  Image1: {
    width: windowWidth * 0.8,
    height: windowWidth * 0.3,
    borderRadius: 20,
  },
});
